const char index_html[] PROGMEM = R"rawliteral(
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#f3f4f1">
  <title>Mini Arm 控制台</title>
  <style>
    :root{--canvas:#f3f4f1;--surface:#fff;--surface-2:#e9ece8;--ink:#17201d;--muted:#65706c;--line:#ccd2ce;--line-strong:#9ba49f;--blue:#1857c9;--blue-soft:#e8effd;--orange:#ed6b2d;--red:#bd2d25;--red-soft:#fbe9e7;--green:#16815f;--shadow:0 12px 30px rgba(23,32,29,.08);--mono:"Cascadia Mono","SFMono-Regular",Consolas,monospace;--sans:"Microsoft YaHei","PingFang SC",system-ui,sans-serif}
    *{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--canvas);color:var(--ink);font-family:var(--sans);letter-spacing:0}button,input{font:inherit}button{cursor:pointer}button:focus-visible,input:focus-visible{outline:3px solid rgba(24,87,201,.28);outline-offset:2px}
    .appbar{min-height:64px;padding:10px 22px;border-bottom:1px solid var(--line);background:rgba(255,255,255,.94);display:flex;align-items:center;gap:18px;position:sticky;top:0;z-index:20;backdrop-filter:blur(14px)}.identity{display:flex;align-items:center;gap:11px;min-width:210px}.logo{width:38px;height:38px;border-radius:8px;background:var(--ink);color:#fff;display:grid;place-items:center;font:800 12px var(--mono)}.name{font-size:15px;font-weight:800}.name small{display:block;margin-top:2px;color:var(--muted);font:600 11px var(--mono)}.live{display:flex;align-items:center;gap:8px;font-size:13px;color:var(--muted);white-space:nowrap}.dot{width:9px;height:9px;border-radius:50%;background:#c99819}.dot.ok{background:var(--green)}.dot.bad{background:var(--red)}.network{font:700 12px var(--mono);padding:7px 9px;border:1px solid var(--line);border-radius:6px;background:var(--canvas);white-space:nowrap}.quick-actions{margin-left:auto;display:flex;align-items:center;gap:8px}
    .btn{min-height:42px;border:1px solid var(--line-strong);border-radius:7px;padding:0 13px;background:var(--surface);color:var(--ink);font-weight:750;transition:background .14s,border-color .14s,transform .14s}.btn:hover{border-color:var(--ink);background:#fafbf9}.btn:active{transform:translateY(1px)}.btn.primary{background:var(--blue);border-color:var(--blue);color:#fff}.btn.primary:hover{background:#1248aa}.btn.ghost-danger{color:var(--red);border-color:#deb7b3}.btn.ghost-danger:hover{background:var(--red-soft);border-color:var(--red)}.btn .symbol{font:800 16px var(--mono);margin-right:6px}
    main{width:min(1480px,100%);margin:0 auto;padding:18px 22px 28px}.status-line{min-height:44px;display:flex;align-items:center;gap:10px;border:1px solid var(--line);background:var(--surface);border-radius:7px;padding:6px 11px;margin-bottom:14px;color:var(--muted);font-size:12px}.status-line b{color:var(--ink)}.status-line .safety{margin-left:auto;color:#7a431a}.status-mark{width:8px;height:8px;background:var(--orange);border-radius:2px}.motion-wrap{display:flex;align-items:center;gap:7px;margin-left:8px}.motion{display:flex;background:var(--surface-2);border-radius:7px;padding:3px;gap:2px}.motion button{min-width:48px;height:29px;border:0;border-radius:5px;background:transparent;color:var(--muted);font-size:11px;font-weight:700}.motion button.active{background:var(--surface);color:var(--blue);box-shadow:0 1px 4px rgba(23,32,29,.14)}
    .workspace{display:grid;grid-template-columns:minmax(330px,380px) minmax(390px,1fr) minmax(292px,340px);border:1px solid var(--line);border-radius:10px;background:var(--surface);box-shadow:var(--shadow);overflow:hidden;min-height:690px}.zone{min-width:0}.zone+.zone{border-left:1px solid var(--line)}.zone-head{height:58px;padding:0 18px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:12px}.zone-head h1,.zone-head h2{font-size:15px;margin:0}.zone-head span{color:var(--muted);font:600 11px var(--mono)}
    .step{display:flex;background:var(--surface-2);border-radius:7px;padding:3px;gap:2px}.step button{min-width:42px;height:31px;border:0;border-radius:5px;background:transparent;color:var(--muted);font:700 12px var(--mono)}.step button.active{background:var(--surface);color:var(--blue);box-shadow:0 1px 4px rgba(23,32,29,.14)}
    .joints{padding:0 18px}.joint{padding:18px 0;border-bottom:1px solid var(--line)}.joint:last-child{border-bottom:0}.joint-head{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:start}.joint-title{font-size:14px;font-weight:800}.joint-title small{display:inline-block;margin-left:6px;color:var(--muted);font:600 11px var(--mono)}.joint-desc{color:var(--muted);font-size:11px;margin-top:4px}.readout{text-align:right;font:850 24px var(--mono);line-height:1}.readout small{font-size:12px;color:var(--muted)}.target{display:block;margin-top:5px;color:var(--muted);font:600 10px var(--mono)}
    .range{width:100%;height:28px;margin:12px 0 3px;accent-color:var(--blue);cursor:pointer}.range-meta{display:flex;justify-content:space-between;color:var(--muted);font:600 10px var(--mono)}.joint-actions{display:flex;align-items:center;gap:7px;margin-top:10px}.nudge{display:grid;grid-template-columns:44px 44px;gap:6px}.nudge button{height:42px;border:1px solid var(--line-strong);border-radius:6px;background:var(--surface);color:var(--ink);font:800 18px var(--mono)}.nudge button:hover{border-color:var(--blue);color:var(--blue);background:var(--blue-soft)}.home-mark{margin-left:auto;color:var(--muted);font-size:11px}.home-mark b{display:block;margin-top:2px;color:var(--ink);font:750 13px var(--mono)}.grip-button{margin-left:auto;min-width:110px}
    .stage-zone{display:flex;flex-direction:column;background:#fafbf9}.stage{position:relative;flex:1;min-height:500px;display:grid;place-items:center;padding:24px;overflow:hidden}.stage:before{content:"";position:absolute;left:8%;right:8%;bottom:14%;border-top:1px solid var(--line)}.arm-svg{width:min(100%,570px);height:auto;overflow:visible}.arm-link{stroke:var(--ink);stroke-width:19;stroke-linecap:round}.arm-link-inner{stroke:#fff;stroke-width:7;stroke-linecap:round;opacity:.88}.joint-node{fill:var(--orange);stroke:var(--ink);stroke-width:5}.joint-core{fill:var(--surface);stroke:var(--ink);stroke-width:3}.arm-base{fill:var(--ink)}.yaw-ring{fill:none;stroke:var(--line-strong);stroke-width:2;stroke-dasharray:3 5}.yaw-marker{stroke:var(--orange);stroke-width:4;stroke-linecap:round}.grip-line{stroke:var(--ink);stroke-width:8;stroke-linecap:round}.diagram-label{font:700 12px var(--mono);fill:var(--muted)}.axis-value{font:800 13px var(--mono);fill:var(--ink)}.pose-strip{border-top:1px solid var(--line);display:grid;grid-template-columns:repeat(4,1fr);background:var(--surface)}.pose-cell{min-height:80px;padding:14px;border-right:1px solid var(--line)}.pose-cell:last-child{border-right:0}.pose-cell label{display:block;color:var(--muted);font-size:11px;margin-bottom:6px}.pose-cell strong{font:800 21px var(--mono)}.pose-cell strong small{font-size:11px;color:var(--muted)}.stage-note{position:absolute;top:18px;left:18px;max-width:245px;color:var(--muted);font-size:11px;line-height:1.55}.stage-note b{color:var(--ink)}
    .calibration{padding:18px}.calibration-intro{font-size:12px;line-height:1.6;color:var(--muted);margin:0 0 15px}.calibration-intro b{color:var(--ink)}.home-fields{display:grid;gap:9px}.home-field{display:grid;grid-template-columns:1fr 88px;align-items:center;gap:10px}.home-field span{font-size:12px;color:var(--muted)}.home-field span b{display:block;color:var(--ink);font-size:13px;margin-bottom:2px}.input-wrap{height:42px;border:1px solid var(--line-strong);border-radius:6px;display:flex;align-items:center;background:var(--surface)}.input-wrap input{width:100%;min-width:0;border:0;background:transparent;padding:0 4px 0 10px;color:var(--ink);font:800 15px var(--mono);outline:0}.input-wrap em{padding-right:9px;color:var(--muted);font:normal 11px var(--mono)}.home-actions{display:grid;gap:8px;margin-top:16px}.home-actions .btn{width:100%}.save-note{font-size:11px;line-height:1.55;color:var(--muted);background:var(--canvas);border-radius:6px;padding:10px;margin:12px 0 0}.safety-panel{margin-top:18px;padding-top:17px;border-top:1px solid var(--line)}.safety-panel h3{font-size:13px;margin:0 0 10px}.safety-list{margin:0;padding:0;list-style:none;display:grid;gap:9px}.safety-list li{display:grid;grid-template-columns:22px 1fr;gap:7px;color:var(--muted);font-size:11px;line-height:1.5}.safety-list b{width:20px;height:20px;display:grid;place-items:center;border-radius:50%;background:var(--surface-2);color:var(--ink);font:700 10px var(--mono)}
    .toast{position:fixed;right:20px;bottom:20px;z-index:30;max-width:min(360px,calc(100% - 28px));padding:12px 14px;background:var(--ink);color:#fff;border-radius:7px;box-shadow:0 14px 34px rgba(23,32,29,.24);font-size:13px;opacity:0;transform:translateY(10px);pointer-events:none;transition:opacity .18s,transform .18s}.toast.show{opacity:1;transform:none}
    @media(max-width:1100px){.workspace{grid-template-columns:350px 1fr}.calibration-zone{grid-column:1/-1;border-left:0!important;border-top:1px solid var(--line)}.calibration{display:grid;grid-template-columns:1fr 1fr;gap:0 24px}.calibration-intro,.home-fields,.home-actions,.save-note{grid-column:1}.safety-panel{grid-column:2;grid-row:1/6;margin:0;padding:0 0 0 24px;border:0;border-left:1px solid var(--line)}}
    @media(max-width:760px){.appbar{padding:9px 12px;gap:10px;flex-wrap:wrap}.identity{min-width:0}.name small,.network{display:none}.live{margin-left:auto}.quick-actions{order:3;width:100%;margin:0;display:grid;grid-template-columns:1fr 1fr}.quick-actions .btn:last-child{grid-column:1/-1}main{padding:10px}.status-line{align-items:center;flex-wrap:wrap}.status-line>span:not(.safety),.status-line .safety{display:none}.motion-wrap{margin-left:auto}.workspace{display:block;min-height:0}.zone+.zone{border-left:0;border-top:1px solid var(--line)}.stage{min-height:390px}.stage-note{top:12px;left:12px}.pose-cell{min-height:70px;padding:11px 8px}.pose-cell label{font-size:10px}.pose-cell strong{font-size:17px}.calibration{display:block}.safety-panel{margin-top:18px;padding:17px 0 0;border-left:0;border-top:1px solid var(--line)}.zone-head{height:54px}.joints{padding:0 14px}.joint{padding:15px 0}}
    @media(max-width:430px){.logo{width:34px;height:34px}.name{font-size:14px}.quick-actions .btn{padding:0 8px;font-size:12px}.stage{min-height:330px;padding:18px 8px 8px}.stage-note{max-width:190px}.pose-strip{grid-template-columns:repeat(2,1fr)}.pose-cell:nth-child(2){border-right:0}.pose-cell:nth-child(-n+2){border-bottom:1px solid var(--line)}.home-field{grid-template-columns:1fr 84px}}
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition:none!important}}
  </style>
</head>
<body>
  <header class="appbar"><div class="identity"><div class="logo">ARM</div><div class="name">Mini Robot Arm<small>XIAO ESP32-S3 · 4 AXIS</small></div></div><div class="live"><i class="dot" id="dot"></i><span id="connectionText">正在连接</span></div><div class="network" id="ip">10.10.10.1</div><div class="quick-actions"><button class="btn primary" id="goHome"><span class="symbol">⌂</span>回到 Home</button><button class="btn" id="saveHome"><span class="symbol">+</span>当前姿态设为 Home</button><button class="btn ghost-danger" id="factoryHome"><span class="symbol">↺</span>恢复默认</button></div></header>
  <main>
    <div class="status-line"><i class="status-mark"></i><b id="lastAction">等待 ESP32 返回状态…</b><span>角度为程序输出值</span><div class="motion-wrap"><span>运动</span><div class="motion" aria-label="运动速度"><button data-motion="smooth" class="active">柔和</button><button data-motion="standard">标准</button><button data-motion="fast">快速</button></div></div><span class="safety">舵机 5V 电源需与 XIAO 共地</span></div>
    <section class="workspace">
      <section class="zone control-zone">
        <div class="zone-head"><div><h1>关节控制</h1><span>拖动滑块或逐步微调</span></div><div class="step" aria-label="微调步长"><button data-step="1" class="active">1°</button><button data-step="5">5°</button><button data-step="10">10°</button></div></div>
        <div class="joints">
          <article class="joint"><div class="joint-head"><div><div class="joint-title">底座左右 <small>LR · D2</small></div><div class="joint-desc">旋转整条机械臂</div></div><div class="readout"><span id="lrNow">90</span><small>°</small><span class="target">目标 <b id="lrTarget">90°</b></span></div></div><input class="range" id="lr" data-axis="lr" type="range" min="10" max="170" value="90" aria-label="底座左右角度"><div class="range-meta"><span>左 10°</span><span>右 170°</span></div><div class="joint-actions"><div class="nudge"><button data-axis="lr" data-dir="-1" aria-label="底座向左微调">−</button><button data-axis="lr" data-dir="1" aria-label="底座向右微调">+</button></div><div class="home-mark">已保存 Home<b id="lrHome">90°</b></div></div></article>
          <article class="joint"><div class="joint-head"><div><div class="joint-title">大臂前后 <small>FB · D3</small></div><div class="joint-desc">控制第一节臂俯仰</div></div><div class="readout"><span id="fbNow">90</span><small>°</small><span class="target">目标 <b id="fbTarget">90°</b></span></div></div><input class="range" id="fb" data-axis="fb" type="range" min="10" max="170" value="90" aria-label="大臂前后角度"><div class="range-meta"><span>后 10°</span><span>前 170°</span></div><div class="joint-actions"><div class="nudge"><button data-axis="fb" data-dir="-1" aria-label="大臂向后微调">−</button><button data-axis="fb" data-dir="1" aria-label="大臂向前微调">+</button></div><div class="home-mark">已保存 Home<b id="fbHome">90°</b></div></div></article>
          <article class="joint"><div class="joint-head"><div><div class="joint-title">小臂上下 <small>UD · D4</small></div><div class="joint-desc">控制第二节臂高度</div></div><div class="readout"><span id="udNow">90</span><small>°</small><span class="target">目标 <b id="udTarget">90°</b></span></div></div><input class="range" id="ud" data-axis="ud" type="range" min="10" max="170" value="90" aria-label="小臂上下角度"><div class="range-meta"><span>下 10°</span><span>上 170°</span></div><div class="joint-actions"><div class="nudge"><button data-axis="ud" data-dir="-1" aria-label="小臂向下微调">−</button><button data-axis="ud" data-dir="1" aria-label="小臂向上微调">+</button></div><div class="home-mark">已保存 Home<b id="udHome">90°</b></div></div></article>
          <article class="joint"><div class="joint-head"><div><div class="joint-title">夹爪开合 <small>GRIP · D5</small></div><div class="joint-desc">按实物方向确认开合</div></div><div class="readout"><span id="gripNow">180</span><small>°</small><span class="target">目标 <b id="gripTarget">180°</b></span></div></div><input class="range" id="grip" data-axis="grip" type="range" min="55" max="180" value="180" aria-label="夹爪开合角度"><div class="range-meta"><span>合 55°</span><span>开 180°</span></div><div class="joint-actions"><div class="nudge"><button data-axis="grip" data-dir="-1" aria-label="夹爪减小角度">−</button><button data-axis="grip" data-dir="1" aria-label="夹爪增大角度">+</button></div><button class="btn grip-button" id="toggleGrip">切换开合</button></div></article>
        </div>
      </section>
      <section class="zone stage-zone">
        <div class="zone-head"><div><h2>姿态预估</h2><span>按当前实物照片校正方向</span></div><span>ESTIMATE</span></div>
        <div class="stage"><p class="stage-note"><b>不是传感器反馈</b><br>按照片校正舵盘方向与零点；实际姿态仍受装配偏齿和连杆间隙影响。</p><svg class="arm-svg" viewBox="0 0 420 390" role="img" aria-label="机械臂姿态预估图"><ellipse class="yaw-ring" cx="210" cy="318" rx="105" ry="30"/><g id="yawMarker"><line class="yaw-marker" x1="210" y1="318" x2="292" y2="318"/><circle cx="292" cy="318" r="5" fill="#ed6b2d"/></g><rect class="arm-base" x="153" y="286" width="114" height="42" rx="8"/><rect fill="#ffffff" opacity=".18" x="169" y="297" width="82" height="9" rx="4"/><line id="link1" class="arm-link" x1="210" y1="286" x2="290" y2="205"/><line id="link1Inner" class="arm-link-inner" x1="210" y1="286" x2="290" y2="205"/><line id="link2" class="arm-link" x1="290" y1="205" x2="352" y2="150"/><line id="link2Inner" class="arm-link-inner" x1="290" y1="205" x2="352" y2="150"/><circle class="joint-node" cx="210" cy="286" r="19"/><circle class="joint-core" cx="210" cy="286" r="7"/><circle id="elbowOuter" class="joint-node" cx="290" cy="205" r="17"/><circle id="elbowInner" class="joint-core" cx="290" cy="205" r="6"/><g id="gripperGroup"><circle class="joint-node" cx="352" cy="150" r="14"/><line id="gripTop" class="grip-line" x1="361" y1="143" x2="388" y2="126"/><line id="gripBottom" class="grip-line" x1="361" y1="157" x2="388" y2="174"/></g><text class="diagram-label" x="126" y="352">BASE ROTATION</text><text class="axis-value" id="diagramValue" x="210" y="372" text-anchor="middle">LR 90° · FB 90° · UD 90°</text></svg></div>
        <div class="pose-strip"><div class="pose-cell"><label>底座 LR</label><strong><span id="poseLr">90</span><small>°</small></strong></div><div class="pose-cell"><label>大臂 FB</label><strong><span id="poseFb">90</span><small>°</small></strong></div><div class="pose-cell"><label>小臂 UD</label><strong><span id="poseUd">90</span><small>°</small></strong></div><div class="pose-cell"><label>夹爪</label><strong><span id="poseGrip">180</span><small>°</small></strong></div></div>
      </section>
      <aside class="zone calibration-zone">
        <div class="zone-head"><div><h2>开机姿态</h2><span>HOME CALIBRATION</span></div><span>FLASH</span></div>
        <div class="calibration"><p class="calibration-intro"><b>先试运行，再保存。</b> 保存后即使断电，下一次启动也会使用这组角度。</p><div class="home-fields"><label class="home-field"><span><b>底座左右</b>LR · 10–170°</span><div class="input-wrap"><input id="homeInputLr" type="number" min="10" max="170" step="1" value="90"><em>°</em></div></label><label class="home-field"><span><b>大臂前后</b>FB · 10–170°</span><div class="input-wrap"><input id="homeInputFb" type="number" min="10" max="170" step="1" value="90"><em>°</em></div></label><label class="home-field"><span><b>小臂上下</b>UD · 10–170°</span><div class="input-wrap"><input id="homeInputUd" type="number" min="10" max="170" step="1" value="90"><em>°</em></div></label><label class="home-field"><span><b>夹爪开合</b>Grip · 55–180°</span><div class="input-wrap"><input id="homeInputGrip" type="number" min="55" max="180" step="1" value="180"><em>°</em></div></label></div><div class="home-actions"><button class="btn" id="previewHome"><span class="symbol">▷</span>试运行这组角度</button><button class="btn primary" id="saveHomeAngles"><span class="symbol">✓</span>保存为开机姿态</button></div><p class="save-note" id="statusHint">这里保存的是舵机软件角度。若舵盘安装偏了一齿，显示 90° 时实物也可能不水平。</p><section class="safety-panel"><h3>首次校准顺序</h3><ol class="safety-list"><li><b>1</b><span>让机械臂悬空，确认外部 5V 电源与 XIAO 共地。</span></li><li><b>2</b><span>选择 1° 步长，每次只调整一个关节。</span></li><li><b>3</b><span>遇到卡住、抖动或明显发热，立即回退角度。</span></li><li><b>4</b><span>姿态确认安全后，再保存为 Home。</span></li></ol></section></div>
      </aside>
    </section>
  </main>
  <div class="toast" id="toast" role="status" aria-live="polite"></div>
  <script>
    const axes=['lr','fb','ud','grip'];let step=1,lastSend=0,statusTimer=0,sendTimer=0,sendInFlight=false,commandDirty=false,manualUntil=0,homeEditorDirty=false;const $=id=>document.getElementById(id);
    function showToast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),2400)}
    function setConnection(ok){$('dot').className='dot '+(ok?'ok':'bad');$('connectionText').textContent=ok?'ESP32 已连接':'连接已断开'}
    function setLine(id,x1,y1,x2,y2){const el=$(id);el.setAttribute('x1',x1);el.setAttribute('y1',y1);el.setAttribute('x2',x2);el.setAttribute('y2',y2)}
    function updateArm(p){const lr=Number(p.lr??90),fb=Number(p.fb??90),ud=Number(p.ud??90),grip=Number(p.grip??180);const rad=Math.PI/180,base={x:210,y:286},a1=(192-1.45*fb)*rad,a2=a1+(ud-122)*rad,l1=116,l2=92;const elbow={x:base.x+Math.cos(a1)*l1,y:base.y+Math.sin(a1)*l1},tip={x:elbow.x+Math.cos(a2)*l2,y:elbow.y+Math.sin(a2)*l2};setLine('link1',base.x,base.y,elbow.x,elbow.y);setLine('link1Inner',base.x,base.y,elbow.x,elbow.y);setLine('link2',elbow.x,elbow.y,tip.x,tip.y);setLine('link2Inner',elbow.x,elbow.y,tip.x,tip.y);['elbowOuter','elbowInner'].forEach(id=>{$(id).setAttribute('cx',elbow.x);$(id).setAttribute('cy',elbow.y)});const spread=7+(grip-55)/125*18,reach=30,normal=a2+Math.PI/2;const head=$('gripperGroup').querySelector('circle');head.setAttribute('cx',tip.x);head.setAttribute('cy',tip.y);setLine('gripTop',tip.x+Math.cos(normal)*7,tip.y+Math.sin(normal)*7,tip.x+Math.cos(a2)*reach+Math.cos(normal)*spread,tip.y+Math.sin(a2)*reach+Math.sin(normal)*spread);setLine('gripBottom',tip.x-Math.cos(normal)*7,tip.y-Math.sin(normal)*7,tip.x+Math.cos(a2)*reach-Math.cos(normal)*spread,tip.y+Math.sin(a2)*reach-Math.sin(normal)*spread);$('yawMarker').setAttribute('transform','rotate('+(lr-90)+' 210 318)');$('diagramValue').textContent='LR '+lr+'° · FB '+fb+'° · UD '+ud+'°'}
    function updateValues(pose){if(!pose)return;const current=pose.current||pose.target||{},target=pose.target||current,keepLocal=Date.now()<manualUntil||sendInFlight||commandDirty;axes.forEach(a=>{if(target[a]!=null){if(!keepLocal){$(a).value=target[a];$(a+'Target').textContent=target[a]+'°'}$(a+'Now').textContent=current[a]??target[a];$('pose'+a[0].toUpperCase()+a.slice(1)).textContent=current[a]??target[a]}});updateArm(current);if(pose.motion)document.querySelectorAll('.motion button').forEach(b=>b.classList.toggle('active',b.dataset.motion===pose.motion));if(pose.home){axes.forEach(a=>{const el=$(a+'Home');if(el)el.textContent=pose.home[a]+'°'});if(!homeEditorDirty){$('homeInputLr').value=pose.home.lr;$('homeInputFb').value=pose.home.fb;$('homeInputUd').value=pose.home.ud;$('homeInputGrip').value=pose.home.grip}}if(pose.ip)$('ip').textContent=pose.ip;$('lastAction').textContent='状态已同步 · '+new Date().toLocaleTimeString()}
    function homeForm(){const ids={lr:'homeInputLr',fb:'homeInputFb',ud:'homeInputUd',grip:'homeInputGrip'};const q=new URLSearchParams();for(const [axis,id] of Object.entries(ids)){const input=$(id);if(!input.reportValidity())return null;q.set(axis,input.value)}return q}
    async function applyHomeConfig(save){const q=homeForm();if(!q)return;q.set('save',save?'1':'0');try{const r=await fetch('/home/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:q.toString()});if(!r.ok)throw Error();const pose=await r.json();homeEditorDirty=!save;updateValues(pose);showToast(save?'已保存，下次开机使用这组角度':'正在试运行，尚未写入闪存');$('lastAction').textContent=save?'开机姿态已保存':'正在试运行候选姿态'}catch(e){setConnection(false);showToast('设置失败，请检查与 ESP32 的连接')}}
    async function getStatus(){if(sendInFlight||commandDirty){statusTimer=setTimeout(getStatus,180);return}try{const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw Error();updateValues(await r.json());setConnection(true)}catch(e){setConnection(false)}finally{statusTimer=setTimeout(getStatus,400)}}
    function localTarget(){const p={};axes.forEach(a=>{p[a]=Number($(a).value);$(a+'Target').textContent=p[a]+'°'});updateArm(p);return p}
    function queueServoSend(immediate=false){commandDirty=true;manualUntil=Date.now()+500;localTarget();clearTimeout(sendTimer);const wait=immediate?0:Math.max(0,45-(Date.now()-lastSend));sendTimer=setTimeout(flushServoSend,wait)}
    async function flushServoSend(){if(sendInFlight)return;if(!commandDirty)return;commandDirty=false;sendInFlight=true;lastSend=Date.now();const p=localTarget(),q=new URLSearchParams(p);try{const r=await fetch('/servo?'+q.toString(),{cache:'no-store'});if(!r.ok)throw Error();setConnection(true)}catch(e){setConnection(false)}finally{sendInFlight=false;if(commandDirty)queueServoSend(true)}}
    document.querySelectorAll('.range').forEach(el=>{el.addEventListener('input',()=>{queueServoSend();$('lastAction').textContent='正在调整 '+el.dataset.axis.toUpperCase()+' · '+el.value+'°'});el.addEventListener('change',()=>queueServoSend(true));});document.querySelectorAll('.step button').forEach(el=>el.addEventListener('click',()=>{step=Number(el.dataset.step);document.querySelectorAll('.step button').forEach(b=>b.classList.toggle('active',b===el));showToast('微调步长已设为 '+step+'°')}));document.querySelectorAll('.motion button').forEach(el=>el.addEventListener('click',async()=>{try{const r=await fetch('/motion?mode='+el.dataset.motion,{cache:'no-store'});if(!r.ok)throw Error();updateValues(await r.json());showToast('运动档位：'+el.textContent)}catch(e){setConnection(false)}}));document.querySelectorAll('.nudge button').forEach(el=>el.addEventListener('click',async()=>{const axis=el.dataset.axis,delta=Number(el.dataset.dir)*step;manualUntil=Date.now()+500;try{const r=await fetch('/jog?axis='+axis+'&delta='+delta,{cache:'no-store'});if(!r.ok)throw Error();updateValues(await r.json());$('lastAction').textContent=axis.toUpperCase()+' 微调 '+(delta>0?'+':'')+delta+'°'}catch(e){setConnection(false);showToast('微调失败，请检查连接')}}));
    $('toggleGrip').addEventListener('click',()=>{$('grip').value=Number($('grip').value)<115?180:60;queueServoSend(true);showToast('夹爪目标已切换')});$('goHome').addEventListener('click',async()=>{try{const r=await fetch('/home');if(!r.ok)throw Error();updateValues(await r.json());showToast('正在回到已保存的 Home')}catch(e){setConnection(false)}});$('saveHome').addEventListener('click',async()=>{try{const r=await fetch('/home/save');if(!r.ok)throw Error();homeEditorDirty=false;updateValues(await r.json());showToast('当前姿态已保存为 Home')}catch(e){setConnection(false)}});document.querySelectorAll('.home-field input').forEach(el=>el.addEventListener('input',()=>homeEditorDirty=true));$('previewHome').addEventListener('click',()=>applyHomeConfig(false));$('saveHomeAngles').addEventListener('click',()=>applyHomeConfig(true));$('factoryHome').addEventListener('click',async()=>{if(!confirm('恢复默认 Home（关节约 90°，夹爪打开）？机械臂会立即移动。'))return;try{const r=await fetch('/home/factory');if(!r.ok)throw Error();homeEditorDirty=false;updateValues(await r.json());showToast('已恢复默认 Home')}catch(e){setConnection(false)}});updateArm({lr:90,fb:90,ud:90,grip:180});getStatus();
  </script>
</body>
</html>
)rawliteral";
